### ISSUE TITLE
websocket implementation cannot be specified

### ISSUE THREAD

**Issue by Semisol** [nbd-wtf/nostr-tools#100]
there is no way to use a WebSocket implementation like `ws` in Node since the implementation cannot be configured. should be easy to do.

**Comment by fiatjaf** [comment]
Isn't `ws`'s API completely different from the HTML5 WebSocket?

**Comment by adamritter** [comment]
You can use nostr-relaypool which uses isomorphic-ws and has
autoreconnecting support as well when the Relay times out. Also it can
store subscriptions even before the connection establishes, and
resubscribes automatically on reconnecting.

**Comment by fiatjaf** [comment]
I believe most of these features are anti-patterns.

**Comment by adamritter** [comment]
I know, that's why I forked the implementation (i usually prefer to have 1
implementation and contribute). Still, it's good to offer choice.

**Comment by fiatjaf** [comment]
In that case you can do `global.WebSocket = require('ws')` and be done with it.

**Comment by fiatjaf** [comment]
I'll accept a PR if you open it.
