### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: wordlist nostr-tools.js:6:8

### ISSUE THREAD

**Issue by melvincarvalho** [nbd-wtf/nostr-tools#101]
Trying to import from skypack:

> import nostrtools from 'https://cdn.skypack.dev/nostr-tools'

Gives strange error in console:

> Uncaught SyntaxError: ambiguous indirect export: wordlist [nostr-tools.js:6:8]

https://cdn.skypack.dev/-/nostr-tools@v1.2.1-kClri916AS4yJkPUcPZx/dist=es2019,mode=imports/optimized/nostr-tools.js

In that file there is:

>   exports.wordlist = void 0;
>   exports.wordlist = `abandon

**Comment by fiatjaf** [comment]
I don't understand what that means.

**Comment by melvincarvalho** [comment]
Yeah me either, I'll see if I can figure it out.

https://www.skypack.dev/

This is a great tool that lets you import packages, but something is going wrong somewhere.

**Comment by fiatjaf** [comment]
You really hate build tools.

**Comment by melvincarvalho** [comment]
Another for comparison / debug:

https://esm.sh/nostr-tools

( still figuring this out )
