### ISSUE TITLE
As a PHP developer who has not used node.js before, how can I quickly get started with this project?

### ISSUE THREAD

**Issue by leijiabin12581** [nbd-wtf/nostr-tools#108]
As a PHP developer who has not used node.js before, how can I quickly get started with this project?

I have installed cygwin64 and just. Then I ran just build and a directory of lib appeared with some files "nostr.bundle.js, nostr.cjs.js, nostr.esm.js, etc." I created a file "1.js" in the root directory and wrote the following code in it:

import {generatePrivateKey, getPublicKey} from 'nostr-tools'

let sk = generatePrivateKey() // sk is a hex string
let pk = getPublicKey(sk) // pk is a hex string

Then I ran node 1.js and got some error messages. I know it's because I don't understand node.js, but I just want to quickly start using this library for development and don't want to spend too much time learning node.js.

**Comment by fiatjaf** [comment]
Use this: https://github.com/nbd-wtf/nostr-tools#using-from-the-browser-if-you-dont-want-to-use-a-bundler

**Comment by jilv220** [comment]
Do you want to use this browser side or node side?
