### ISSUE TITLE
tsc iterable errors

### ISSUE THREAD

**Issue by rolznz** [nbd-wtf/nostr-tools#116]
Hi, I cannot get this to work, even changing my tsconfig file (I tried both setting "target" to "ES2015" and setting "downlevelIteration" to true.

```yarn run v1.22.19
$ tsc -noEmit
node_modules/nostr-tools/pool.ts(55,22): error TS2802: Type 'IterableIterator<() => void>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
node_modules/nostr-tools/pool.ts(64,24): error TS2802: Type 'IterableIterator<(event: Event) => void>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
node_modules/nostr-tools/pool.ts(72,26): error TS2802: Type 'IterableIterator<() => void>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
error Command failed with exit code 1.```

(This library is consumed in a NextJS project)

**Comment by fiatjaf** [comment]
I don't understand what is the problem there, but I also don't understand TypeScript.

I have never actually run `tsc`, I am just running the TypeScript LSP server and and transpiling the code with https://esbuild.github.io/. The types look ok for these two tools apparently.

Can't you import the library JavaScript bundles?

**Comment by rolznz** [comment]
I don't really understand either, but fixed it in my own code. It seems like I had some conflict with the libs I was using in my tsconfig file.
![image](https://user-images.githubusercontent.com/33993199/219573592-95994197-fc51-470e-98f7-2d64e6229926.png)
