### ISSUE TITLE
TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by nicolasburtey** [nbd-wtf/nostr-tools#119]
I have this error:

```
TypeError: Cannot read properties of undefined (reading 'push')
at Object.on (/app/node_modules/nostr-tools/lib/nostr.cjs.js:524:34)
at file:///app/src/relay.js:108:15
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

from this file: https://github.com/GaloyMoney/galoy-nostr/blob/main/src/relay.js#L108

the error is not systematic. appears maybe on 50% of the relays.

any clue why that is?

**Comment by ktecho** [comment]
Hi Nicolas,

The `seen` event was removed from `nostr-tools` a few versions ago. I think fiatjab said something like it didn't work fine, or something.

The problem will go away when you remove lines 108 to 111 in that file :)
