### ISSUE TITLE
nip19.neventEncode silently fails

### ISSUE THREAD

**Issue by offbyn** [nbd-wtf/nostr-tools#129]
I'd expect this to fail with an error, but it just silently stops, second console.log does not log.

```js
    console.log(nip19.neventEncode('string-but-should-be-event'));
    console.log('whoot? where is my error?');
```

wrapping in try/catch to see what is going on, shows the expected error.

```js
    try {
      console.log(nip19.neventEncode(event.id));
    } catch(e) { console.error(e); }
    console.log('whoot? where is my error?');
```

returns `TypeError: hexToBytes: expected string, got undefined`

**Comment by fiatjaf** [comment]
I don't understand.

![2023-02-24-093811_852x162_scrot](https://user-images.githubusercontent.com/1653275/221180895-ff694f03-9a5d-4eb7-986e-60316fa1754a.png)
