### ISSUE TITLE
Followers list dropped when you follow somebody

### ISSUE THREAD

**Issue by bokybanton** [nbd-wtf/nostr-tools#131]
This issue also happens with relay list. As NIP-02 said: "_Every new contact list that gets published overwrites the past ones, so it should contain all entries. Relays and clients SHOULD delete past contact lists as soon as they receive a new one.__ something related to this on library makes you follow only one npub and "forget" or delete the others you were following.

Could be related with max bytes accepted by relays? I don't know but I will appreciate help with this issue! I hope I can understand if it is a bug or it is clients fault.

**Comment by fiatjaf** [comment]
The issue is not related to this library. It is some client somewhere doing things wrong and overwriting your follow lists. Use https://coracle.social/ or https://github.commikedilger/gossip.
