### ISSUE TITLE
Trouble decoding naddr

### ISSUE THREAD

**Issue by ChristianChiarulli** [nbd-wtf/nostr-tools#134]
I'm not sure if this is an issue with the nip19 module or if habla.news is rolling there own way to handle decoding naddrs but for the following address: `naddr1qq98yetxv4ex2mnrv4esygrl54h466tz4v0re4pyuavvxqptsejl0vxcmnhfl60z3rth2xkpjspsgqqqw4rsf34vl5` I'm running into an issue when trying to decode with:

`const naddr = nip19.decode(naddrStr).data;`

![image](https://user-images.githubusercontent.com/29136904/221387365-6ad427a2-1646-4749-9314-6612029ba01f.png)

Seems to be an issue when retrieving the relays: https://github.com/nbd-wtf/nostr-tools/blob/master/nip19.ts#L74

link working on habla.news: https://habla.news/a/naddr1qq98yetxv4ex2mnrv4esygrl54h466tz4v0re4pyuavvxqptsejl0vxcmnhfl60z3rth2xkpjspsgqqqw4rsf34vl5

link not working on blogstack.io: https://blogstack.io/naddr1qq98yetxv4ex2mnrv4esygrl54h466tz4v0re4pyuavvxqptsejl0vxcmnhfl60z3rth2xkpjspsgqqqw4rsf34vl5

**Comment by fiatjaf** [comment]
Oops. Yes, this was a bug on nostr-tools. Fixed at 27749d91b890ce45214bcf6771897c613e73f856.
