### ISSUE TITLE
Inconsistency Readme example vs type definitions

### ISSUE THREAD

**Issue by Egge7** [nbd-wtf/nostr-tools#136]
The code example for "Interacting with multiple relays" suggests that pool.sub will take an Array of either URLs as strings or the return value of pool.ensureRelay as first parameter.

From the Readme:
### Interacting with multiple relays

```js
import {SimplePool} from 'nostr-tools'

const pool = new SimplePool()

let relays = ['wss://relay.example.com', 'wss://relay.example2.com']

let relay = await pool.ensureRelay('wss://relay.example3.com')

let sub = pool.sub([...relays, relay], [{
  authors: ['32e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245']
}])
```

--- 

However according to the type definition pool.sub() expects an Array of strings as parameter while pool.ensureRelay returns an object of type Relay. Therefore `relay` can't be a valid parameter for pool.sub

**Comment by fiatjaf** [comment]
This is true.
