### ISSUE TITLE
nip19.decode fails when nprofile `relays` is empty

### ISSUE THREAD

**Issue by staab** [nbd-wtf/nostr-tools#147]
```
nip19.decode(nip19.nprofileEncode({pubkey: '97c70a44366a6535c145b333f973ea86dfdc2d7a99da618c40c64705ad98e322', relays: []}))
```

Throws:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at Object.decode (nostr.esm.js:820:24)
```

**Comment by fiatjaf** [comment]
Are you on the latest version? That was fixed some time ago I think. I've added a test on https://github.com/nbd-wtf/nostr-tools/commit/01435ab9f5d58201ee1b362ac95293056d688d2c for your specific case here.

**Comment by staab** [comment]
I ran into it when I tested the PR you submitted on coracle, but I just realized I didn't re-install deps, that's probably the problem.

**Comment by fiatjaf** [comment]
I don't understand JavaScript so I might have done everything wrong again.

**Comment by staab** [comment]
Nope, just rm -rf'd node_modules and it fixed the issue
