### ISSUE TITLE
nip-01: are prefixed authors and ids supported?

### ISSUE THREAD

**Issue by offbyn** [nbd-wtf/nostr-tools#157]
> The ids and authors lists contain lowercase hexadecimal strings, which may either be an exact 64-character match, or a prefix of the event value.

https://github.com/nostr-protocol/nips/blob/master/01.md

I am trying to subscribe with a filter for ids of ['0000'] with the intention to only receive events with some minimum POW eventId.

After figuring out the events are received but 'event' is not fired (see https://github.com/scsibug/nostr-rs-relay/issues/104) I wonder if prefixed id's are supported by `nostr-tools` or if this is a bug.

**Comment by offbyn** [comment]
in this fiddle events starting with 0000 are received but somehow nostr-tools doesn't fire the event https://jsfiddle.net/syr4k235/

**Comment by fiatjaf** [comment]
They were technically supported but as you found out there was a bug, then the support was officially removed from the NIPs.
