### ISSUE TITLE
Has anyone tried using this in a NuxtJS project?

### ISSUE THREAD

**Issue by bilthon** [nbd-wtf/nostr-tools#163]
I found several issues while trying to do that, fixed many, but I'm currently stuck with this weird one that is apparently caused by a dependency.

```
weierstrass.ts?d966:1068 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at SWUFpSqrtRatio (weierstrass.ts?d966:1068:1)
    at mapToCurveSimpleSWU (weierstrass.ts?d966:1137:1)
    at eval (secp256k1.ts?3ff4:250:1)
    at ./node_modules/@noble/curves/secp256k1.js (app.js:155:1)
    at __webpack_require__ (runtime.js:854:30)
    at fn (runtime.js:151:20)
    at eval (index.js?8c36:1:1)
    at ./node_modules/@scure/bip32/lib/esm/index.js (app.js:251:1)
    at __webpack_require__ (runtime.js:854:30)
```

This is a run-time error I just see in the browser.

**Comment by akhavr** [comment]
Fighting for a week with this bug in https://github.com/akhavr/nostrya/issues/3

Now cleaned to the dumbest possible react page with minimal dependencies.  Yet failing.

Freshly created project doesn't give that trace.

**Comment by fiatjaf** [comment]
Can you use sourcemaps to try to trace that? Are you using NIP-06?

**Comment by bilthon** [comment]
The error seems to be [this](https://github.com/paulmillr/noble-secp256k1/issues/64) one. I'm not sure how to restrict browser targets for nuxtjs, just adding a simple `browserlists` definition to package.json didn't make it work.

**Comment by akhavr** [comment]
> The error seems to be [this](https://github.com/paulmillr/noble-secp256k1/issues/64) one. I'm not sure how to restrict browser targets for nuxtjs, just adding a simple `browserlists` definition to package.json didn't make it work.

https://github.com/akhavr/nostrya/issues/3#issuecomment-1481565826 fixed it for me.
