### ISSUE TITLE
SimplePool publish callbacks broken

### ISSUE THREAD

**Issue by Egge7** [nbd-wtf/nostr-tools#169]
I think one of the latest releases broke pub callbacks (?). Have not found time to debug yet, but pub.on('ok', cb) is no longer being fired for me. Can anyone reproduce?

**Comment by talhasch** [comment]
@Egge7 I'm having same problem too.

**Comment by georgeburduhos** [comment]
It is an issue for me too

**Comment by fiatjaf** [comment]
Fixed in v1.8.2.
