### ISSUE TITLE
Question about filtering by tags: how to get events without e tags 

### ISSUE THREAD

**Issue by rayliao** [nbd-wtf/nostr-tools#182]
For example, how should I distinguish between note events and reply events to notes, which have e tags, and how should I filter with tags when I only want to get note events and want to exclude reply events?

I thought about adding an extra tag to differentiate or taking out all the data and then filtering, but I don't think that's the best way to do it, thanks.

**Comment by fiatjaf** [comment]
That's an old question and we don't have a way to do it yet. Probably an empty array in the filter would indicate that we want events without such tags, but I'm not sure if this is practical. Would be a nice NIP to propose and get feedback from relay authors.
