### ISSUE TITLE
Expose ws.onClose

### ISSUE THREAD

**Issue by joshr4** [nbd-wtf/nostr-tools#191]
I'm using this lib in a web app project, and am running into an issue where my relay connection closes after 2-3 minutes. I'm connected up to a nostream relay, and my assumption is that the relay is closing the socket connection.

In order to work around this, I check the relay status, and when it is in a `closing` or `closed` state, I call `relay.connect()` again.
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/readyState#value

I think a better approach would be to add a `ws.onClose` listener that auto-reconnects using a `setTimeout`.

Relevant line in `nostr-tools` https://github.com/nbd-wtf/nostr-tools/blob/master/relay.ts#L112

I'd like to expose this function via `nostr-tools`, I plan to make a PR with this change.

**Comment by joshr4** [comment]
Does anyone else experience this behavior? How do you handle unexpected socket closure by a relay?

**Comment by fiatjaf** [comment]
I see, yes, we could add this. But I would very much prefer that relays don't think it's normal to close connections with no reason. If a relay is closing a connection it should be because it doesn't want you connected to it, so in that case it's a bad idea to create auto-reconnect flows. @Cameri what do you think?

**Comment by joshr4** [comment]
Yeah good point, I'll investigate the relay side of things some more and try to determine what is happening there. That sounds like the "right" way to fix my issue.

**Comment by Cameri** [comment]
@joshr4 Please create a bug ticket on the Nostream repo. By default Nostream disconnects any client without an active subscription, but if the client does have a subscription and still disconnects it could be a bug.
Keep in mind it's possible that proxies are the ones dropping the connection regardless after 2 mins which is a different but related issue.

**Comment by joshr4** [comment]
> @joshr4 Please create a bug ticket on the Nostream repo. By default Nostream disconnects any client without an active subscription, but if the client does have a subscription and still disconnects it could be a bug.
> Keep in mind it's possible that proxies are the ones dropping the connection regardless after 2 mins which is a different but related issue.

We recently discovered the disconnect was most likely being caused by a default timeout setting in nginx. I will close this issue out, I had forgotten about it 😅
