### ISSUE TITLE
ReferenceError: crypto is not defined (not in browser)

### ISSUE THREAD

**Issue by joelklabo** [nbd-wtf/nostr-tools#192]
Getting this error trying to run my code on a Ubuntu server, it has been working locally on my Mac. 

```
file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-tools/lib/esm/nostr.mjs:1022
  let cryptoKey = await crypto.subtle.importKey(
                  ^

ReferenceError: crypto is not defined
    at Object.encrypt (file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-tools/lib/esm/nostr.mjs:1022:19)
    at NostrDMBot.publish (file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-dm-bot/nostr-dm-bot.js:53:25)
    at NostrDMBot.<anonymous> (file:///home/azureuser/.lightning/plugins/nostr-control/nostr-control.js:20:12)
    at NostrDMBot.emit (node:events:513:28)
    at file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-dm-bot/nostr-dm-bot.js:16:9
    at file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-tools/lib/esm/nostr.mjs:322:43
    at Array.forEach (<anonymous>)
    at ws.onopen (file:///home/azureuser/.lightning/plugins/nostr-control/node_modules/nostr-tools/lib/esm/nostr.mjs:322:27)
    at EventTarget.dispatchEvent (/home/azureuser/.lightning/plugins/nostr-control/node_modules/websocket-polyfill/lib/events/EventTarget.js:33:17)
    at WebSocket._Handle_connect (/home/azureuser/.lightning/plugins/nostr-control/node_modules/websocket-polyfill/lib/WebSocket.js:200:14)

Node.js v18.14.2
```

**Comment by LAMike310** [comment]
A quick fix that I used was adding ```const crypto = require("crypto");``` on line 723 in `nostr.cjs.js`, not the best solution, but it works for now

**Comment by joelklabo** [comment]
> A quick fix that I used was adding `const crypto = require("crypto");` on line 723 in `nostr.cjs.js`, not the best solution, but it works for now

Thanks! I'll try that. This is what I see on that line though. Mind sharing a diff? I might have a different version or something:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/264977/233129832-0becbbcd-8a16-4985-a00f-f7eabba58529.png">

**Comment by fiatjaf** [comment]
Try `global.crypto = require('crypto')` or something like that.

**Comment by joelklabo** [comment]
> Try `global.crypto = require('crypto')` on your server code, or something like that.

Thanks, I'll try that. Any idea why it happens? It works on one machine and not the other both recent node versions. Just curious 🤷🏼‍♂️

**Comment by fiatjaf** [comment]
I have no idea of why it happens, no, but I've experienced that myself. I forgot how I fixed. It was very weird, because for me too it was two recent Node versions, one was 18 and the other 19 I think. The Node docs says it has support for the same Crypto APIs the browser has by default without having to import anything, but maybe that is only on Node 19? I don't know.

**Comment by joelklabo** [comment]
I guess I'm not allowed to do that in ES module world...

```
globalThis.crypto = crypto;
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
    at file:///Users/honk/code/nostr-control/nostr-control.js:10:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.5.0
```

**Comment by LAMike310** [comment]
> > A quick fix that I used was adding `const crypto = require("crypto");` on line 723 in `nostr.cjs.js`, not the best solution, but it works for now
> 
> Thanks! I'll try that. This is what I see on that line though. Mind sharing a diff? I might have a different version or something: <img alt="image" width="410" src="https://user-images.githubusercontent.com/264977/233129832-0becbbcd-8a16-4985-a00f-f7eabba58529.png">

I guess you can put it anywhere, but I placed the import right before the line of ```async function encrypt(privkey, pubkey, text)```

**Comment by joelklabo** [comment]
I did the same but it the .mjs bc I'm using import.

**Comment by ldover** [comment]
Also bumped into this issue in Node. `require('crypto')` didn't work for me, but `global.crypto =  require('node:crypto').webcrypto;` fixed it.

**Comment by joelklabo** [comment]
Is there a way this could be fixed from Typescript by adding this import? Or does that cause other issues?
