### ISSUE TITLE
Tests should be in TypeScript

### ISSUE THREAD

**Issue by alexgleason** [nbd-wtf/nostr-tools#206]
One last thing - if the tests were in TypeScript it would be easier to test changes to types. I might convert them if you agree.

**Comment by fiatjaf** [comment]
I tried to write them in TypeScript, but Jest wouldn't allow me at all, it would just scream and die no matter what I tried. I you can do that it will be great. Also if there's a better way to run the tests that doesn't involve Jest I'm all for it.
