### ISSUE TITLE
should SubscriptionOptions supports getTimeout eoseSubTimeout etc?

### ISSUE THREAD

**Issue by Eosxx** [nbd-wtf/nostr-tools#212]
Opts `getTimeout` of `relayInit` is as global settings. `relay.get(filter)`  can not send request as two different`getTimeout`.

Make `SubscriptionOptions` of `Sub` accept `getTimeout`, we can

```javascript
// use global/default `getTimeout`, return data after 3s
// get 1000 event
relay.get(filter) 

// use custome `getTimeout`, return data after 10s
// get more than 1000 event
relay.get(filter, { getTimeout: 10000 })
```

`SimplePool` is the same way.

**Comment by alexgleason** [comment]
Agreed timeout should be per-query. I'm planning to build a new pool module at some point with strategy options such as "race" and "all"
