### ISSUE TITLE
Some errors on an old version of typescript: 3.8.3

### ISSUE THREAD

**Issue by colaru** [nbd-wtf/nostr-tools#215]
I get these errors on my project because I use an old version of typescript:
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"

For some reasons, I  can't migrate to a new version of typescript (I see that this project is using "typescript": "^5.0.4")
Any idea how to solve this? The only solution I see is to fork the library and to fix it...

See the errors I get:

ERROR in node_modules/nostr-tools/lib/filter.d.ts:10:11 - error TS1110: Type expected.

10     [key: `#${string}`]: string[];
             ~~~~
node_modules/nostr-tools/lib/filter.d.ts:10:23 - error TS1005: ';' expected.

10     [key: `#${string}`]: string[];
                         ~
node_modules/nostr-tools/lib/filter.d.ts:10:24 - error TS1128: Declaration or statement expected.

10     [key: `#${string}`]: string[];
                          ~
node_modules/nostr-tools/lib/filter.d.ts:10:33 - error TS1011: An element access expression should take an argument.

10     [key: `#${string}`]: string[];
                                   
node_modules/nostr-tools/lib/filter.d.ts:11:1 - error TS1128: Declaration or statement expected.

11 };
   ~
node_modules/nostr-tools/lib/nip21.d.ts:10:56 - error TS1110: Type expected.

10 export declare function test(value: unknown): value is `nostr:${string}`;
                                                          ~~~~~~~~~
node_modules/nostr-tools/lib/nip21.d.ts:14:10 - error TS1110: Type expected.

14     uri: `nostr:${string}`;
            ~~~~~~~~~
node_modules/nostr-tools/lib/nip21.d.ts:19:1 - error TS1128: Declaration or statement expected.

19 }
   ~

**Comment by alexgleason** [comment]
Template literal types were added in TypeScript 4.1: https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html

There's nothing to do except upgrade TypeScript.

**Comment by fiatjaf** [comment]
Why can't you upgrade TypeScript?

**Comment by colaru** [comment]
Ooh. Hi, Pater Nostr. I didn't know that you were active here.
I have a chain of old dependencies: ionic > angular -> typescript, and I don't have time now to fix the 'dependencies hell.' 
For simplicity, I will fix these compilation problems on a fork of nostr-tools. I will migrate later...

**Comment by fiatjaf** [comment]
OK.
