### ISSUE TITLE
signEvent - React native - [TypeError: undefined is not a function]

### ISSUE THREAD

**Issue by jinglescode** [nbd-wtf/nostr-tools#216]
I have tested on Next.js, it works. but on react native, an error `TypeError: undefined is not a function` occurred on `signEvent(event, sk);`:

```js
    let event = {
      kind: 1,
      pubkey: pk,
      created_at: Math.floor(Date.now() / 1000),
      tags: [],
      content: message,
    };
    event.id = getEventHash(event);
    event.sig = signEvent(event, sk); // error [TypeError: undefined is not a function]
```

**Comment by alexgleason** [comment]
What happens if you do this?

```js
    let event = finishEvent({
      kind: 1,
      pubkey: pk,
      created_at: Math.floor(Date.now() / 1000),
      tags: [],
      content: message,
    }, sk);
```

It is functionally equivalent to your code above.

**Comment by jinglescode** [comment]
Thanks for your reply. 

Doing 
```
    let event = finishEvent({
      kind: 1,
      pubkey: pk,
      created_at: Math.floor(Date.now() / 1000),
      tags: [],
      content: message,
    }, sk);
```

Results in this error:

```
ReferenceError: Property 'pka' doesn't exist
```

Before this error, there was the `TextDecoder doesn't exist`. I fixed it with `import 'text-encoding-polyfill';`.

Do you know of any resources for react native (no expo)?

**Comment by alexgleason** [comment]
Sorry, I don't know. :thinking:

**Comment by Eosxx** [comment]
```javascript
import * as secp256k1 from '@noble/secp256k1';
import { randomBytes } from 'react-native-randombytes';

secp256k1.utils.randomBytes = function (bytesLength = 32) {
  return Uint8Array.from(randomBytes(bytesLength));
};
```

Try set it in entry file like `App.tsx`

**Comment by jinglescode** [comment]
> ```js
> import * as secp256k1 from '@noble/secp256k1';
> import { randomBytes } from 'react-native-randombytes';
> 
> secp256k1.utils.randomBytes = function (bytesLength = 32) {
>   return Uint8Array.from(randomBytes(bytesLength));
> };
> ```
> 
> Try set it in entry file like `App.tsx`

Same error. I will log `nostr-tools` and see which line is causing this issue.
