### ISSUE TITLE
how to use custom kinds

### ISSUE THREAD

**Issue by earonesty** [nbd-wtf/nostr-tools#217]
tool like "finishEvent" espect "kind" to be in a certain range, which i rarely use

whats the best way to deal with this?  can force cast, but is there an expected way to do  it?

**Comment by alexgleason** [comment]
@fiatjaf We should do a release with the type improvements. That will fix this.

**Comment by alexgleason** [comment]
Specifically 8a53b3b8b3fb28a41ec3213437a36f25372cb7f1 will allow you to use `signEvent<number>(event)` to sign any type of event.

The latest changes now make `Event<K>` a generic type. If you use the relay or pool modules with filters, it will be inferred from filters. So a filter like `{ kinds: [1, 2, 3] }` will return events of type `Event<1 | 2 | 3>`

**Comment by fiatjaf** [comment]
Published v1.11.1 with the new type improvements. Sorry for the delay.
