### ISSUE TITLE
nip19.decode() does not return in some case

### ISSUE THREAD

**Issue by murachue** [nbd-wtf/nostr-tools#223]
I found that following code does not return and eating memory. (using Node.js v18.14.0, nostr-tools 1.10.0)

```js
require('nostr-tools').nip19.decode('nevent1qq5v4rkz')
```

I think [here (parseTLV)](https://github.com/nbd-wtf/nostr-tools/blob/bb5acfc19764d1c4e46bba6b1065ef4a25121951/nip19.ts#L125-L127) is the thing happening.
Since with above example `l` (`rest[1]`) is `undefined`, and `2 + l` = `undefined`, it does `rest.slice(undefined)` which is noop, and `v.length < l` is `false` and `push`ing `v` to `result`.  (eating memory.) And `rest` is still not changed, loop continues forever.

I expect it throws an Error if such broken (incomplete) input is given.
I've tested this with older nostr-tools but I think it still left on current master. (bb5acfc19764d1c4e46bba6b1065ef4a25121951)

**Comment by alexgleason** [comment]
Lol this is catastrophic. Simply requesting a URL on my server with this nostr ID `nevent1qq5v4rkz` makes the CPU go up to 100% and never come down until the server is restarted.

**Comment by alexgleason** [comment]
Before the request:

![Screenshot from 2023-06-08 08-21-33](https://github.com/nbd-wtf/nostr-tools/assets/3639540/04561ad5-ca1c-40d7-aa21-f4afefa9bf3c)

After making the request and even closing the tab:

![Screenshot from 2023-06-08 08-18-43](https://github.com/nbd-wtf/nostr-tools/assets/3639540/3f644fc8-5dbc-451f-80d6-e0104ed33b74)

**Comment by fiatjaf** [comment]
No way. This must be a joke.

**Comment by murachue** [comment]
I confirmed it throws "Error: malformed TLV 0" for nevent1qq5v4rkz with nostr-tools 1.11.2
Thanks for quick fix!

**Comment by 3bl3gamer** [comment]
It is broken again, likely after https://github.com/nbd-wtf/nostr-tools/commit/566437fe2e040966301f0292b2f4041be0abc362

When `rest` is `[0]`, the `parseTLV` never returns and eats memory. Same example:
```js
require('nostr-tools').nip19.decode('nevent1qq5v4rkz')
```

Checked with `nostr-tools@2.23.3`.
