### ISSUE TITLE
Is it safe to encrypt data for your own pubkey?

### ISSUE THREAD

**Issue by alexgleason** [nbd-wtf/nostr-tools#227]
I want to encrypt some data for myself only, and put it on a relay. Later I want to fetch and decrypt it. Is it safe to `nip04.encrypt(mySecretKey, myPubkey, message)` ?

(I will be relying on NIP-07 and Nostr Connect implementations, so I won't actually have access to the secret key. It's really a question of whether I can use `window.nostr.nip04.encrypt(myPubkey, message)` safely. So, I can't use a different encryption function.)

cc @paulmillr

**Comment by fiatjaf** [comment]
Lots of people are doing it. Would be better to move to nip44. We could probably deploy that on nos2x as an experimental feature while major clients don't decide to move all DMs to that.

**Comment by paulmillr** [comment]
@fiatjaf sounds good, but need to make a few adjustments to pull request and create a secure library for its cryptography primitives. Also incorporating your feedback.
