### ISSUE TITLE
SimplePool.list() will prioritize older content from an outdated relay over newer content from a live relay with regards to the filter limit.

### ISSUE THREAD

**Issue by efraimbart** [nbd-wtf/nostr-tools#229]
If you call SimplePool.list() on a couple relays with one of them being an outdated relay with only stale data, the returned list will potentially be limited to older data even if there are relays with much newer data.

**Comment by alexgleason** [comment]
This is a general Nostr problem. You want intelligent relay selection. [NDK](https://github.com/nostr-dev-kit/ndk) looks promising.
