### ISSUE TITLE
How can i perform a following event

### ISSUE THREAD

**Issue by maksmachado** [nbd-wtf/nostr-tools#232]
Hello friends,

I have been reading the NIp documentation, but I couldn't find any mention of how to trigger an event that record  a user following another user. I would appreciate any help or information regarding this matter. Thank you in advance.

**Comment by fiatjaf** [comment]
This: https://github.com/nostr-protocol/nips/blob/master/02.md

**Comment by maksmachado** [comment]
Thanks
