### ISSUE TITLE
Strange behavior when trying to fetch event kind 0

### ISSUE THREAD

**Issue by maksmachado** [nbd-wtf/nostr-tools#233]
Hello friend,
I am using the following code to submit an event of kind 0:

`const privateKey = NostrTools.generatePrivateKey();
            const publicKey = NostrTools.getPublicKey(privateKey);

            const pool = new NostrTools.SimplePool();
            const event = {
                kind: 0,
                created_at: Math.floor(Date.now() / 1000),
                tags: [],
                pubkey: publicKey,
                name: userName.value,
                content: ''
                
            }

            const standardPicture = `https://domain.com/picture`

            event.about = about.value === '' ? `standard about` : about.value;
            event.picture = picture.value === '' ? standardPicture : picture.value;
            if(displayName.value !== '') event.display_name = displayName.value;

            console.log(event);
            

            event.id = NostrTools.getEventHash(event);
            event.sig = NostrTools.getSignature(event, privateKey);
            console.log("id =>"+event.id);

            const pub = pool.publish(relayList, event);`

the submit workes fine, however, whe i try to fetch this event using the following code:

`
const pool = new NostrTools.SimplePool();
    const publicKey = localStorage.getItem("publicKey");
    console.log(publicKey);

    const sub = pool.sub([...relayList], [
        {
            kinds:[0],
            authors: [publicKey]
        }
    ]);
    
    
    sub.on('event', event => {
        console.log(event);
    });
`

it returns a object with only required properties, like:
{
content
created_at
id
kind
pubkey
sig
tags
}

**Comment by maksmachado** [comment]
Thanks man. And sorry about the question, but some details escape our perception. this was overlook

**Comment by alexgleason** [comment]
You should close the issues where your question was answered.
