### ISSUE TITLE
Getting error TS2305: Module has no exported member

### ISSUE THREAD

**Issue by sebastianmontero** [nbd-wtf/nostr-tools#235]
I have a typescript package in which I'm including the nostr-tools package, when I try to build it using tsc, I'm getting errors like the following error: 
error TS2305: Module '"nostr-tools"' has no exported member 'Kind'

It happens with every member I try to import from the package: Event, getSignature, etc.

This happens with version: 1.12.0  the strange thing is that with version 1.7.4 I have no issues.

Any idea what could be the issue?

**Comment by sebastianmontero** [comment]
This is the info on my environment:

```

 System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 13.07 GB / 31.06 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.133
  npmPackages:
    tsdx: ^0.14.1 => 0.14.1 
    typescript: ^4.9.4 => 4.9.4 
```

**Comment by michaelhall923** [comment]
Same issue, typescript 4.8.4

Everything works fine in dev, just build fails.

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": "./"
  },
  "include": ["next-env.d.ts", "webln-types.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by alexgleason** [comment]
Have you tried upgrading TypeScript? It's on 5.x now.

**Comment by michaelhall923** [comment]
will try

**Comment by michaelhall923** [comment]
Upgrading typescript to 5.0.0 fixed it.

**Comment by alexgleason** [comment]
Not sure why the error happens. I guess it has something to do with TypeScript enums being bad. I'm tempted to make it not an enum... maybe. But glad to hear upgrading TypeScript fixed it.
