### ISSUE TITLE
How to perform an efficient search for mentions?

### ISSUE THREAD

**Issue by maksmachado** [nbd-wtf/nostr-tools#236]
Hello friends, I'm trying to implement a solution to perform a mention search. The idea is to analyze the user's text for each 'input' event and identify a name typed with '@'. Then, search a pool of relays using the 'search' property of NIP-50.
The problem with this implementation is that the result brings tons of possible matches (and very slow result), and none of them come very close to the string used in the search. My question is whether there is a more efficient way to perform this search. Below is the code:
`

```
var pool = new NostrTools.SimplePool();
textarea.addEventListener('input', (e) => {
                    const text = e.target.textContent;
                    const matchMention = text.match(/@[^\s@]+$/g);                    
                    if(matchMention && matchMention[0].length > 3) {             
                       
                        var name = matchMention[0].replace('@', '');
                        const search = `"name":"${name}`;
                       const sub = pool.sub([...relayList],[
                            {
                                kinds: [0],
                                search: search,
                            }
                        ]);

                        sub.on('event', event => {
                            const content = JSON.parse(event.content);
                            const regExpName = new RegExp(name);

                            if(content.name.match(regExpName)) {
                                console.log(event.content);

                            }
                        
                        })
                                                       

                })
```

**Comment by fiatjaf** [comment]
```js
{
  "kinds": [1],
  "#p": [pubkeymentioned]
}
```

**Comment by maksmachado** [comment]
But if the client do not know the public key. the idea is to get the name provided by the user directly from the text, in principle the client would not know the public key of the person mentioned

**Comment by maksmachado** [comment]
the idea is to get the name given by the user directly from the text. In principle, the client would not know the public key of the mentioned person. As in the NIP-27 example, where the client offers an autocomplete when the user types Bob

**Comment by fiatjaf** [comment]
There is no way to do this unless you download all posts and do the search manually.

**Comment by maksmachado** [comment]
I've thought a lot about this case today, and the best idea that came to mind would be to create a contact list up to the fourth level of depth, starting from the user in question, and then limit the search to that list. Otherwise, request the inclusion of the (pk).
