### ISSUE TITLE
This library wants to use zod

### ISSUE THREAD

**Issue by alexgleason** [nbd-wtf/nostr-tools#246]
zod: https://github.com/colinhacks/zod

I've avoided it because it's an extra dependency. But it makes hard tasks of validation much easier. For example, here's how you validate a signed event:

```ts
import { z } from 'zod';

import { verifySignature } from './event.ts';

const hex256Schema = z.string().regex(/^[0-9a-f]{64}$/);

const signedEventSchema = z.object({
  id: hex256Schema,
  kind: z.number(),
  tags: z.array(z.array(z.string())),
  content: z.string(),
  created_at: z.number(),
  pubkey: hex256Schema,
  sig: z.string(),
}).refine(verifySignature);

type SignedEvent = z.infer<typeof signedEventSchema>;
```

Then you can:

```ts
const event = signedEventSchema.parse(data) // will either throw, or return a SignedEvent
```

I'm afraid it might be too big of a change, so I'm considering making a separate `nostr-schema` library. Here's an example of using Zod for a much harder thing in Nostr, validating a NIP-98 auth event: https://gitlab.com/soapbox-pub/ditto/-/blob/develop/src/middleware/auth98.ts#L24

**Comment by zeevo** [comment]
+1 for Zod!

**Comment by wbobeirne** [comment]
@fiatjaf yes: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

**Comment by fiatjaf** [comment]
Let's not use this for now.
