### ISSUE TITLE
Can't resolve '@scure/bip39/wordlists/english' ... because it was resolved as fully specified

### ISSUE THREAD

**Issue by polkhovsky** [nbd-wtf/nostr-tools#253]
This is the error I'm getting right after installing the module and trying to generate private key:

ERROR in ./node_modules/nostr-tools/lib/esm/nostr.mjs 1206:0-58
Module not found: Error: Can't resolve '@scure/bip39/wordlists/english' in '/Users/alex/projects/nostr-client/node_modules/nostr-tools/lib/esm'
Did you mean 'english.js'?
BREAKING CHANGE: The request '@scure/bip39/wordlists/english' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by ubinix-warun** [comment]
@polkhovsky I got same problem, and fix it by install nostr-tools and @scure/bip39 in local package.

**Comment by alexgleason** [comment]
Seems like a dependencies-of-dependencies issue. Maybe @paulmillr knows what `Error: Can't resolve '@scure/bip39/wordlists/english'` means.

**Comment by pavanjoshi914** [comment]
if you use scure/bip39 in your package.json. update it to the latest version i.e 1.2.1.  this solved the issue. 

in our case, we have secure/bip39 in package.json and also nostr-tools depends on scure/bip39 probably there was somewhat version incompability there

**Comment by erskingardner** [comment]
Running into this as well but I can't seem to manually update in a way that gets it working...

**Comment by paulmillr** [comment]
nostr-tools needs to update all its dependencies to the most recent ones

https://github.com/nbd-wtf/nostr-tools/blob/c1848d78a0e796408b7499a53abad52add3367a4/package.json#L26

Anyone willing to submit a pull request? Needs to become this:

```
    "@noble/curves": "1.1.0",
    "@noble/hashes": "1.3.1",
    "@scure/base": "1.1.1",
    "@scure/bip32": "1.3.1",
    "@scure/bip39": "1.2.1"
```

**Comment by pavanjoshi914** [comment]
@paulmillr i have updated other dependencies as well in the pr #254
