### ISSUE TITLE
How to get profile info? (e.g. name, image)

### ISSUE THREAD

**Issue by decentropy** [nbd-wtf/nostr-tools#256]
Not an issue, just seeking help...

Between NIP-19 and nip-19.ts, I can't put it together.
Appreciate if anyone can explain how to fetch name/image/etc from an npub or pubkey

**Comment by fiatjaf** [comment]
We need a group running on Nostr for developer questions like this. Maybe ask on StackOverflow or on https://t.me/nostr_protocol?

The short answer is to read NIP-01.

**Comment by decentropy** [comment]
agreed. it'd feel right to use nostr if possible...

maybe if there was standard hashtag, repos could link & people could follow? nostr communities have a bit of overhead

https://nostr.band/note1nqeet8zq0knctrwwh4gup4dfqxr0c8unf648ds6547e9xf9xmayqndc0sd

**Comment by ptrio42** [comment]
I'm building https://swarmstr.com mainly for this. It's in an early phase, buggy and slow but I'm committing most of my free time to make it work.

**Comment by telamon** [comment]
@decentropy IDK if my approach is correct but i just looked it up using a separate subscription:
```js
const profile = await new Promise(resolve => {
  let p = null
  const sub = pool.sub(relays, [
    { kinds: [0], authors: ['HEX_PUBKEY'] }
  ])
  sub.on('event', event => {
    if (!p || p.created_at < event.created_at) p = event
  })
  sub.on('eose', () => {
    sub.unsub()
    resolve(p)
  })
})
```

**Comment by decentropy** [comment]
thanks yep, the replies here helped... event kind 0 (per NIP-01)
