### ISSUE TITLE
NIP-07 (extension) not working in chrome

### ISSUE THREAD

**Issue by decentropy** [nbd-wtf/nostr-tools#260]
Below works in Firefox (to trigger extension e.g. Alby).
In Chrome or Chromium, on first page load it gives "Cannot read properties of undefined (reading 'getPublicKey')".  On following tries, no error nothing happens.

Same occurs with Alby, Nos2x extensions... so I believe it's problem with nostr-tools

```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/nostr-tools/lib/nostr.bundle.js"></script>
</head>
<body>

  <script>   
  // Everything loaded...
  document.addEventListener('DOMContentLoaded', function() {

    window.nostr.getPublicKey()
    .then((result) => {
      console.log("getPublicKey:", result); 
    })
    .catch((error) => {
      console.error("Error:", error);
    });
  });
      
</script>
</body>
</html>
```

**Comment by alexgleason** [comment]
`window.nostr` is provided by the extension, not nostr-tools. In your example you don't invoke nostr-tools code at all, just a useless import. Try calling `window.nostr.getPublicKey` after clicking a button instead of on pageload.

**Comment by decentropy** [comment]
I see... okay thank you
