### ISSUE TITLE
NIP-26 describes delegations with multiple kinds, but nip26.createDelegation(..) only takes one kind as argument

### ISSUE THREAD

**Issue by iijat** [nbd-wtf/nostr-tools#266]
[NIP-26](https://github.com/nostr-protocol/nips/blob/master/26.md) shows a valid condition string with multiple kinds for **one** delegation:

- kind=0&kind=1&created_at>1675721813

The method ```nip26.createDelegation(...)``` however only takes one kind as argument and not an array of kinds.

**Comment by fiatjaf** [comment]
NIP-26 has been removed.
