### ISSUE TITLE
The subscription data limit in ReactNative is set to 500, but the result is always less than 500 entries

### ISSUE THREAD

**Issue by jiangwei1995** [nbd-wtf/nostr-tools#285]
**I am using ReactNative. Why did the first code obtain less than 500 pieces of data? The second code can**

Version: **"nostr-tools": "^1.10.1",**

**First paragraph of code**
```
const testSub = async () => {
      const pool = new SimplePool();
      let sub = pool.sub(
        ['wss://relay.damus.io'],
        [
          {
            kinds: [42],
            '#e': [
              '4dcbcee477c49d851209206a7ec945d1c3584c4411954de689030ec000f2c256',
            ],
            limit: 500,
          },
        ],
      );
      let i = 0;
      const list: any[] = [];
      sub.on('event', event => {
        i++;
        list.push({
          i,
          created_at: event.created_at,
          id: event.id,
          content: event.content,
        });
      });

      sub.on('eose', () => {
        console.log(unionBy(list, 'id').length);
        console.log('eose:', list.length);
      });
    };
```

**Second paragraph of code**
 ```
const socket = new WebSocket('wss://relay.damus.io');
      socket.onopen = () => {
        console.log('WebSocket connected');
        const subscription = [
          'REQ',
          'REQ-92497957',
          {
            kinds: [42],
            '#e': [
              '4dcbcee477c49d851209206a7ec945d1c3584c4411954de689030ec000f2c256',
            ],
            limit: 500,
          },
        ];
        socket.send(JSON.stringify(subscription));
      };

      let i = 0;
      let start = Date.now();
      socket.onmessage = event => {
        i++;
        if ('["EOSE","REQ-92497957"]' === event.data?.toString()) {
          console.log('OK', i, Date.now() - start);
        }
      };
      socket.onerror = error => {
        console.error('WebSocket error:', error);
      };
```

**Comment by jiangwei1995** [comment]
> Relays will send as many results as they want, there is no requirement about that. The `limit` parameter is just a hint.
@fiatjaf 
Same environment, filter, and time
The first piece of code is to obtain data using nostr tools, The amount of data obtained by nostr tools varies from 50 to 200 each time.
The second section of code uses WebSocket to obtain data, The data obtained using WebSocket has always been 500 documents

**Comment by Egge7** [comment]
SimplePool will fake an EOSE after 3400ms if not told otherwise. You will still receive events after that point.

@fiatjaf Maybe we should add an option to disable this timeout alltogether?

**Comment by jiangwei1995** [comment]
> 



> SimplePool will fake an EOSE after 3400ms if not told otherwise. You will still receive events after that point. But because you log the length on EOSE, SimplePool will call that callback after 3400ms.
> 
> @fiatjaf Maybe we should add an option to disable this timeout?

SimplePool cannot be used for production, right?
Do you have a recommended implementation of 'SimplePool'?

**Comment by Egge7** [comment]
Try extending your eoseSubTimout option to e.g.. 10000 and see if the issues are resolved.

**Comment by jiangwei1995** [comment]
> 



> Try extending your eoseSubTimout option to e.g.. 10000 and see if the issues are resolved.
Okay, but 10 seconds is too long

I have set eoseSubTimeout to 11000ms

387 pieces of data were obtained using the pool. list method at 11033ms

500 pieces of data were obtained by directly connecting to 1658ms using WebSocket

**Comment by jiangwei1995** [comment]
> > Okay, but 10 seconds is too long
> > I have set eoseSubTimeout to 11000ms
> > Same environment, filter, and time
> > 387 pieces of data were obtained using the pool. list method at 11033ms
> > 500 pieces of data were obtained by directly connecting to 1658ms using WebSocket
> 
> That benchmark is not really a good one, as nostr-tools will parse the received JSON and verify it's signature

Will a public chat event type of 42 also verify signatures?

**Comment by Egge7** [comment]
> Will a public chat event type of 42 also verify signatures?

Yes, you can pass `skipVerification: true` as a Subscription Option to skip that step. JSON parsing will still happen though and takes time.

**Comment by jiangwei1995** [comment]
> > Will a public chat event type of 42 also verify signatures?
> 
> Yes, you can pass `skipVerification: true` as a Subscription Option to skip that step. JSON parsing will still happen though and takes time.

Okay, thank you for your time

**Comment by jiangwei1995** [comment]
> > Will a public chat event type of 42 also verify signatures?
> 
> Yes, you can pass `skipVerification: true` as a Subscription Option to skip that step. JSON parsing will still happen though and takes time.

I have another question, how can Nostr tools keep WebSocket connected for a long time? Do you have any heartbeat messages? Or will it disconnect if there is no message for a long time?

**Comment by Egge7** [comment]
> I have another question, how can Nostr tools keep WebSocket connected for a long time? Do you have any heartbeat messages? Or will it disconnect if there is no message for a long time?

Connections will be dropped after being stale for a while. However Simple Pool will remember connections are re-establish them when needed.

**Comment by Egge7** [comment]
It think this issue can be closed then.
