### ISSUE TITLE
Multiple relays and timestamps

### ISSUE THREAD

**Issue by mroxso** [nbd-wtf/nostr-tools#286]
Is it possible to sort the events based on the created_at field when using multiple relays?

Currently notes/events come in unsorted between multiple relays.

**Comment by fiatjaf** [comment]
The only way is to download the events and sort on the client.

**Comment by Egge7** [comment]
> The only way is to download the events and sort on the client.

I think what they suggest is to let SimplePool sort events by created_at. That would only be possible for all async methods and TBH I think its unnecessary bloat for this package.
