### ISSUE TITLE
Pool connections status

### ISSUE THREAD

**Issue by misovan** [nbd-wtf/nostr-tools#300]
Is there a way to get status (readyState) of connections inside a SimplePool? Thanks

**Comment by Egge7** [comment]
I used a "dirty" workaround for this, accessing the `_conn` property of the SimplePool instance directly. It works, but maybe we should add a getter for Connection state. I'll open a PR

**Comment by fiatjaf** [comment]
I think using the dirty workaround should be fine.

**Comment by Egge7** [comment]
> I think using the dirty workaround should be fine.

I disagree. _conn is a private field that will not even be shown by the LSP. Also accessing it directly is unsafe. A overwrite will render the pool instance useless. Also _conn holds many other private fields of the Relay Instance that are not of interest to the end user of the API.

I am working on a PR that adds a getter method to the class that will return a safe copy of only the connection state and exclude the other methods.

**Comment by antonioconselheiro** [comment]
this pr with `listConnectionStatus()` didn't solve this issue? allow you to see whole network status 
https://github.com/nbd-wtf/nostr-tools/pull/419/files
