### ISSUE TITLE
nevent encode doesnt include kind

### ISSUE THREAD

**Issue by shaibearary** [nbd-wtf/nostr-tools#303]
https://github.com/nbd-wtf/nostr-tools/blob/e899cc32b7aaf5008a85ab4839e10dc8be3577fe/nip19.ts#L19-L23

Im curious about the reason,  nip19 said kind is optional for nevent encoding

**Comment by fiatjaf** [comment]
The reason is that you haven't opened a PR including it.

**Comment by shaibearary** [comment]
well thats a good reason
#304 
ping @fiatjaf
