### ISSUE TITLE
Package does not work when using common js

### ISSUE THREAD

**Issue by sebastianmontero** [nbd-wtf/nostr-tools#309]
When I import the package using require in a common js package and try to list events it always returns an empty array. If I import the package using import in an esm or typescript package everything works.
Does anyone know why this might be?

I'm using version: 1.16.0

**Comment by sebastianmontero** [comment]
Just this:

```const pool = new SimplePool()
      const events = await pool.list(['wss://relay.nostrss.re'], [{kinds:[0]}])
      console.log(events)
```
  Yes legacy project

**Comment by alexgleason** [comment]
Is it possible you need to add the WebSocket polyfill? Per the readme:

> To use this on Node.js you first must install `websocket-polyfill` and import it:
> 
> ```js
> import 'websocket-polyfill'
> ```

**Comment by sebastianmontero** [comment]
Thank you! That worked! Sorry didn't notice that part of the docs.
