### ISSUE TITLE
TypeScript types only for nips?

### ISSUE THREAD

**Issue by mysterybear** [nbd-wtf/nostr-tools#310]
Hi,

if I `bun create` a project, `bun add nostr-tools` and try to import, it only suggests importing the nip's and the utils, not the other modules

**Comment by alexgleason** [comment]
Does it have signEvent ?

**Comment by mysterybear** [comment]
My bad, needed to update VS code so VS code TypeScript version was >5

was trying too much at once what with Bun and all this lol cheers
