### ISSUE TITLE
NIP-44 Migration

### ISSUE THREAD

**Issue by DustinBrett** [nbd-wtf/nostr-tools#311]
I am currently using NIP-04 and interested in moving to NIP-44 as is now shown in https://github.com/nbd-wtf/nostr-tools#encrypting-and-decrypting-direct-messages, but I am thinking to wait until https://github.com/nostr-protocol/nips/pull/746 is merged at least.

When the time does come, I wanted to know how I can migrate and still communicate with users who might not yet be on a NIP-44 capable client. Is there a way to negotiate and go back down to NIP-04? Could a conversation be transitioned to NIP-44 or a combination of NIP-04 and NIP-44?

Also I use nos2x for NIP-07 and until they support NIP-44 (https://github.com/fiatjaf/nos2x/pull/47) I also don't imagine migrating.

**Comment by fiatjaf** [comment]
The audit is finished.

**Comment by DustinBrett** [comment]
> The audit is finished.

Great, thanks for following up! I will close this issue then and begin migration in my codebase to NIP-44's new encryption.
