### ISSUE TITLE
How to filter zaps by tags

### ISSUE THREAD

**Issue by pedromvpg** [nbd-wtf/nostr-tools#319]
What is the best way to list the zaps of an event?
Is there a way to filter zaps by tags?

```
sub = pool.sub(
  relays,
  [{
    kinds: [9735],
    authors: ['be1d89794bf92de5dd64c1e60f6a2c70c140abac9932418fee30c5c637fe9479'],
    tags: [['e','a9dbd94fa68fb83845353b85d3bd50f41289f878f1c576fc1eb3685b163f49f5']]
  },
])
```

**Comment by fiatjaf** [comment]
```
sub = pool.sub(
  relays,
  [{
    kinds: [9735],
    authors: ['be1d89794bf92de5dd64c1e60f6a2c70c140abac9932418fee30c5c637fe9479'],
    '#e': ['a9dbd94fa68fb83845353b85d3bd50f41289f878f1c576fc1eb3685b163f49f5']
  },
])
```

**Comment by fiatjaf** [comment]
What is the `authors` value you're using there?

**Comment by pedromvpg** [comment]
Would be the pubkey that created the note, as in Ably Zapper or Wallet of Satoshi in case the user is using one of these.

your '#e' continues to return no results. Strange. I can see on other clients the zaps are there.

**Comment by pedromvpg** [comment]
Ops, it actually worked. Mixed up my keys

**Comment by fiatjaf** [comment]
You should actually have an `authors` there with the pubkey of the zap provider for that specific user. Somewhat cumbersome.

**Comment by pedromvpg** [comment]
It looks like alby doesn't populate the #e tag. Wallet of satoshi does.

**Comment by fiatjaf** [comment]
That might be because you zapped just a profile, not a specific event.
