### ISSUE TITLE
why doesn't validateEvent return boolean?

### ISSUE THREAD

**Issue by monlovesmango** [nbd-wtf/nostr-tools#321]
general question, why doesn't validateEvent() in event.ts return as a boolean in its signature?

so instead of:
```typescript
export function validateEvent<T>(event: T): event is T & UnsignedEvent<number> {
```

why isn't it this?:
```typescript
export function validateEvent<T>(event: T): boolean {
```

**Comment by alexgleason** [comment]
It does return a Boolean. That's a TypeScript type predicate: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

**Comment by monlovesmango** [comment]
thank you @alexgleason ! appreciate the explanation, still picking up typescript and this is a great to know about!
