### ISSUE TITLE
type definitions for 2.0.0

### ISSUE THREAD

**Issue by syusui-s** [nbd-wtf/nostr-tools#327]
I tried to update to 2.0.0 but I got the following error: `error TS7016: Could not find a declaration file for module 'nostr-tools'.`
It seems that the type definitions are not included in version 2.0.0

There was `types` directory in 1.17.0.
https://www.npmjs.com/package/nostr-tools/v/1.17.0?activeTab=code

There are no `types` directory in 2.0.0.
https://www.npmjs.com/package/nostr-tools/v/2.0.0?activeTab=code

It would be great if you could include type definitions in the new release.

**Comment by fiatjaf** [comment]
Thank you. It's there now on 2.0.1.
