### ISSUE TITLE
Outdated Example API in README: Missing get and list Methods in Relay Class

### ISSUE THREAD

**Issue by richard16611** [nbd-wtf/nostr-tools#337]
The example API in the README appears outdated as the get and list methods are not present in the Relay class:
```
const relay = await Relay.connect('wss://relay.example.com')

let events = await relay.list([{ kinds: [0, 1] }])
let event = await relay.get({
  ids: ['44e1827635450ebb3c5a7d12c1f8e7b2b514439ac10a67eef3d9fd9c5c68e245'],
})

```

These methods were very useful. Could they be considered for reimplementation?

**Comment by ralyodio** [comment]
i find the docs are very wrong at this point. i think the project is abandoned by owner.

**Comment by fiatjaf** [comment]
What else is wrong, @ralyodio?

**Comment by fiatjaf** [comment]
@richard16611 it's better to just use the `SimplePool` and pass a single relay URL as a parameter to `pool.get()` and `pool.querySync()` (same as `.list()`).

**Comment by ralyodio** [comment]
I posted about a no. Working exemplar like a week ago
