### ISSUE TITLE
Include relay URL in error

### ISSUE THREAD

**Issue by fishcharlie** [nbd-wtf/nostr-tools#346]
Currently if you have a pool, and there is an error (I think connecting), there is no way to determine which relay failed.

For example this code:

```typescript
const pool = new nostrtools.SimplePool();
try {
	await Promise.all(pool.publish(socialNetwork.credentials.relays, relayListMetadataEvent));
} catch (e) {
	console.error("Error posting nostr profile relays", e);
}
```

Produces this error for me:

```
Error posting nostr profile relays Server responded with a non-101 status: 403 Forbidden
Response Headers Follow:
server: awselb/2.0
date: Thu, 11 Jan 2024 23:21:41 GMT
content-type: text/html
content-length: 118
connection: keep-alive
```

It would be great if included in that error it told you the URL of the server that failed.

**Comment by fiatjaf** [comment]
`pool.publish()` returns an array of promises that correspond the list of relays given (so if you call `Promise.all()` it will error as long as _any_ relays fail).

To get the relay that failed, do something like:

```js
const pool = new nostrtools.SimplePool();
const pubs = pool.publish(socialNetwork.credentials.relays, relayListMetadataEvent));
pubs.forEach(async (pub, i) => {
  try {
    await pub
  } catch (err) {
    let relay = socialNetwork.credentials.relays[i]
    console.log(`relay ${relay} failed`)
  }
})
```

**Comment by fishcharlie** [comment]
@fiatjaf Not sure why I didn't think of that. I was recently working with this system that didn't maintain order for async code from what you passed in. So that is probably why.

Thanks for the info!
