### ISSUE TITLE
NIP-06 removed from exports?

### ISSUE THREAD

**Issue by josefelbez** [nbd-wtf/nostr-tools#351]
Hey, after updating from 1.17 to 2.1.3 I realized that there is no exports for the nip06 anymore, is there a workaround?

![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/32abb95b-42e1-4e81-9f59-ceef8d88378d)

It is still listed as within the lib but inaccessible, at least not typed

![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/887da9f0-de70-418c-be10-170346164213)

**Comment by fiatjaf** [comment]
Yes, you can do `import * as nip06 from 'nostr-tools/nip06`.

**Comment by josefelbez** [comment]
> Yes, you can do `import * as nip06 from 'nostr-tools/nip06.ts'` or something like that.

Unfortunatelly there is no nostr-tools/nip06.ts, only way is to import from folder cjs or esm but this way we lose types, perhaps is there a better way to keep using the typed one?

**Comment by fiatjaf** [comment]
Sorry, it's `nostr-tools/nip06`.

**Comment by josefelbez** [comment]
> Sorry, it's `nostr-tools/nip06`.

![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/7e8e1060-7eab-4038-a37e-7b0a2e4eb1e5)
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/acceca31-27c7-4d38-a9d6-14c3f6f74816)

**Comment by josefelbez** [comment]
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/a668bb67-b3bf-43b6-8afa-98706d5be24e)

It does not make sense, can you confirm that you are using the same version as me? 2.1.3

![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/805c0def-fd92-42aa-bb56-623fa79d0c47)

**Comment by josefelbez** [comment]
> ![2024-01-18-084243_677x232_scrot](https://private-user-images.githubusercontent.com/1653275/297728552-86bed685-204c-4ac8-a4ea-6f74c2a9099b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Nzk3MzUsIm5iZiI6MTcwNTU3OTQzNSwicGF0aCI6Ii8xNjUzMjc1LzI5NzcyODU1Mi04NmJlZDY4NS0yMDRjLTRhYzgtYTRlYS02Zjc0YzJhOTA5OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTIwMzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZlMGQwZWM5Yzg5ZjE0MzE4ODNkMDVhZGU1NTJkYTk4NzMyOThlYzM0YWYzZGY0NjhhZTNmY2ZkN2I1MWY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZZ7sIuWmyU2XmHEluGoP6JzF2toa3FKJVpzqRuU0Lk0)

please can u reopen the issue?

**Comment by fiatjaf** [comment]
Yes, I am using 2.1.3.

Can you try running it on Node, Deno or Bun?

**Comment by josefelbez** [comment]
> Yes, I am using 2.1.3.
> 
> Can you try running it on Node, Deno or Bun?

Hi, tried with yarn, npm, deno and bun, only bun seems to work.

With yarn:
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/71547dd7-80e9-4598-863f-8f69002b868b)

With npm:
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/f90214db-efd3-4633-ab78-eab2a9a3c2c3)

with bun:
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/af16cb01-5411-4cea-a5c4-98d4828980f6)
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/b8a5b417-36cb-4255-a6cb-0624b3fbc158)

With deno seems to work but no types:
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/2aea43d0-ba82-4eec-ad24-d7671b435440)
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/c3d2530c-fb09-407a-98c4-bd9af75f084d)

**Comment by fiatjaf** [comment]
Then it must be because you're using an old version of TypeScript? I'm guessing, I don't understand this mess.

**Comment by josefelbez** [comment]
![image](https://github.com/nbd-wtf/nostr-tools/assets/12129203/ae90566f-98df-47eb-bad7-e5b4785a4ea5)

Weirdly i'm using ts 5.2.2, but ok. I'll just do a workaround and remove the nip06 from my stuff. 

Thanks for the help

**Comment by fiatjaf** [comment]
I am sorry, but I really don't understand the JS ecosystem. I can barely make it work on my machine.

**Comment by fiatjaf** [comment]
This is the solution: https://stackoverflow.com/a/70020984
