### ISSUE TITLE
Relay Example in Angular

### ISSUE THREAD

**Issue by seanmurphy1661** [nbd-wtf/nostr-tools#367]
Anyone get the relay example to work in angular? I'm getting tons events. I'm just having a mental block on getting them out of the onevent function to manipulate.

**Comment by fiatjaf** [comment]
Like this?

```js
let events = []

relay.subscribe(_, _, {
  onevent(event) {
    events.push(event)
  }
})
```

**Comment by seanmurphy1661** [comment]
V similar to what I had to do. I could not access a component property in the code block, but I can access a var local to the calling function. set the property to the local var,  done. angular can make the simplest thing difficult.
