### ISSUE TITLE
the seenOn method now became a property

### ISSUE THREAD

**Issue by mostafa-khaldi** [nbd-wtf/nostr-tools#371]
Before updating to the new version (I was using 1.7v) the `seenOn` method was used heavily on my project, now it's became a property and I don’t know what to use to replace it, if there is another method that does the same job, please refer to it

**Comment by mostafa-khaldi** [comment]
for anyone facing this issue, I figured out that you should have set `pool.trackRelays = true` and the `pool.seenOn` will return a Map of event IDs with their array of relays in which it exists

**Comment by fiatjaf** [comment]
Thank you for providing this answer.

Yes, as part of the 2.0 release a bunch of breaking changes were introduced, this was one of them. Sorry about that.
