### ISSUE TITLE
wrong index for variant

### ISSUE THREAD

**Issue by FliXii** [nbd-wtf/nostr-tools#385]
Hello, I am trying to retrieve how many relays are still holding a specific message and therefore i am trying to filter for id.

No matter what method for retrieving i use, get, querysnc or subscribemany, i always get:

![image](https://github.com/nbd-wtf/nostr-tools/assets/50446265/32a0c315-7c9b-488f-9f84-9dc8e7ec1b22)

My function looks like this:

![image](https://github.com/nbd-wtf/nostr-tools/assets/50446265/54f596f1-ec01-4f56-8cec-c1af0aea03be)

what am i doing wrong?
Thanks in advance

**Comment by alexgleason** [comment]
The error is coming from the relay, in this case strfry. Do other relays give the same error?

**Comment by fiatjaf** [comment]
What is the id you're giving there? Looks like it's an invalid id.

**Comment by FliXii** [comment]
> What is the id you're giving there? Looks like it's an invalid id.

My functionm for posting a message retourns the proerty field id of an event, this is the one that i am using for the query as parameter id. The code for the post looks like this. 

![image](https://github.com/nbd-wtf/nostr-tools/assets/50446265/e1609c3d-5005-420e-b6f0-23afe782ec18)


Or is the id something else? I thought i must be correct as invalid ids are rejected by the relays. 

Regarding @alexgleason: I have used 5 different relays and as seen two on the screenshot have replied in the same way. I will try also to use some other ones.

**Comment by fiatjaf** [comment]
Try changing your code to this:

```js
const event = await window.nostr.signEvent(baseEvent)
pool.publish(relays, event)
return event.id
```

**Comment by FliXii** [comment]
Hey thanks for the idea, i have tried it out but the resulting Id from your code is identical to the one i used via the hash function. 

![image](https://github.com/nbd-wtf/nostr-tools/assets/50446265/c9c687aa-caa5-41d6-9bfe-db9f2e8fd53d)


Results in 

![image](https://github.com/nbd-wtf/nostr-tools/assets/50446265/2c879b1f-95b9-4bc0-a409-322a5d9b5b63)

**Comment by fiatjaf** [comment]
If you change the pubkey you'll get a different id, that is probably what is happening there.

Anyway, what was your problem again? In your initial post you were getting an error from relays because (I guess) the id you were giving them. If you could run that part again and print out the id you were passing to the `countActiveRelays` function and then I can try it here locally that will be great.

**Comment by FliXii** [comment]
I have resolved the error now, the problem was the type of the id in the function parameters of countActiverelays, it has to be string[] instead of string. Now i dont get the stgfy error anymore from the relays, but still not the message back that i am trying to filter for. But i guess i will figure that or make a new post. Thanks anyways :-)

**Comment by FliXii** [comment]
I have resolved the error now, the problem was the type of the id in the function parameters of countActiverelays, it has to be string[] instead of string. Now i dont get the stgfy error anymore from the relays, but still not the message back that i am trying to filter for. But i guess i will figure that or make a new post. Thanks anyways :-)
