### ISSUE TITLE
nip46.createAccount should accept local keypair

### ISSUE THREAD

**Issue by nostrband** [nbd-wtf/nostr-tools#401]
Currently createAccount generates local keypair internally and sets it into BunkerSigner that is returned. Problem is, local keypair can't be retrieved from the signer, and thus can't be saved to persistent storage to be reused on the next session, and thus user will have to re-connect the app.

**Comment by fiatjaf** [comment]
Like this?

**Comment by nostrband** [comment]
I think that should be enough, now this can be fixed: https://github.com/fiatjaf/window.nostr.js/issues/2
