### ISSUE TITLE
export from nostr-tools the specialized types written in nip19

### ISSUE THREAD

**Issue by antonioconselheiro** [nbd-wtf/nostr-tools#408]
I'm suggesting that specialized types written in nip19 code be exposed from nostr-tools as named symbols.
The `nprofile`, `nrelay`, `nevent`, `naddr`, `nsec`, `npub`, `note`, `ncryptsec` types and a Nip05 type would be very useful to strengthen the types in nostr apps.

Today I'm using like this:

```typescript
export type TNostrPublic = `npub1${string}`;
export type TNostrSecret = `nsec1${string}`;
[...]
export type TNip05 = `${string}@${string}`;
```

but surelly you would like another name

**Comment by antonioconselheiro** [comment]
Would be too much to suggest to include too typescript type guards for these exclusive types?

```typescript
export const nostrTypeGuard = {

  isNostrSecret(nsec: string): nsec is TNostrSecret {
    return /^nsec/.test(nsec);
  }

  isNostrPublic(npub: string): npub is TNostrPublic {
    return /^npub/.test(npub);
  }

  isNcryptsec(ncryptsec: string): ncryptsec is TNcryptsec {
    return /^ncryptsec/.test(ncryptsec);
  }
}
```

The type guard has cast effect, if the string passes in the if with this type guard, it will be recognized by typescript as the specialized type.

![image](https://github.com/nbd-wtf/nostr-tools/assets/91137293/4d55d1b4-727e-4fe4-a581-a0cc5fd75898)

**Comment by fiatjaf** [comment]
I don't know if we gain anything by doing this, but if it doesn't hurt we can have it.

**Comment by antonioconselheiro** [comment]
I'm available to implement this, it's ok if you present a pr of this later?

**Comment by antonioconselheiro** [comment]
I'm closing this because is done and published, no problem?
