### ISSUE TITLE
Missing properties on NIP11 interface

### ISSUE THREAD

**Issue by antonioconselheiro** [nbd-wtf/nostr-tools#415]
Properties `max_subscriptions`, `created_at_lower_limit`, `created_at_upper_limit` and `restricted_writes` are missing in NIP11 Limitations interface.

Implementation:
https://github.com/nbd-wtf/nostr-tools/blob/master/nip11.ts#L107

Docs:
https://github.com/nostr-protocol/nips/blob/master/11.md#extra-fields

**Comment by fiatjaf** [comment]
Please send a PR fixing it.
