### ISSUE TITLE
new nostr-tools release breaks Proof-of-Work based filtering 

### ISSUE THREAD

**Issue by smolgrrr** [nbd-wtf/nostr-tools#428]
I've noticed that filtering for notes with Proof-of-Work no longer works with the latest nostr-tools release. You can replicate the issue with the sample code below:

```const pool = new SimplePool()

const feedRelays = [
  "wss://relay.snort.social",
  "wss://nostr.bitcoiner.social",
  "wss://nostr.mom",
  "wss://relay.nostr.bg",
  "wss://nos.lol",
  "wss://powrelay.xyz",
  "wss://nostr.mutinywallet.com",
];

let h = pool.subscribeMany(
  [...feedRelays],
  [
    {
      ids: ["0000"], // Minimum difficulty
      kinds: [1],
      since: Math.floor((Date.now() * 0.001) - (24 * 60 * 60)),
    },
  ],
  {
    onevent(event) {
      console.log('we got a PoW event:', event)
    },
    oneose() {
      h.close()
    }
  }
)
```

Run this code with release 2.5.1 and you should receive plenty of Proof-of-Work notes. If you run it with 2.7.1/latest, you will receive no response.
Unfortunately I haven't identified the change that broke this.

**Comment by fiatjaf** [comment]
The prefix stuff was removed from the NIPs and most relays have removed support. strfry still has it so that still works on most relays, but the strfry guy has said he will remove support too as soon as he gets some time, so we're dead anyway.

**Comment by smolgrrr** [comment]
it’s over

**Comment by smolgrrr** [comment]
hmmm that really sucks. I don't think there's gonna be a good way to fetch PoW notes in the future, other than fetching all recent notes from relays and then filtering for PoW after that.
