### ISSUE TITLE
export direct message relay list in kinds (10050)

### ISSUE THREAD

**Issue by antonioconselheiro** [nbd-wtf/nostr-tools#433]
gm

maybe this gonna be included when [nip17](https://github.com/nostr-protocol/nips/blob/master/17.md) comes to this library (right?), I do know, but BlockedRelaysList = 10006 and SearchRelaysList = 10007 are included already, why not 10050 too? 😬 😳

nostr-tools/kinds is nice to avoid magic numbers in my code.

**Comment by fiatjaf** [comment]
Learn to love magic numbers.

But also feel free to include all kind numbers you want.

**Comment by antonioconselheiro** [comment]
Thank you, so I'll open a pr to include nip17 kinds.
Learning they meaning is needed to improve debug, but words help code talk to new devs as a mom.
