### ISSUE TITLE
Feature Request: Option to set subscription id in `relay.subscribe()`

### ISSUE THREAD

**Issue by chmac** [nbd-wtf/nostr-tools#439]
Reading through abstract relay, it seems like `prepareSubscription()` accepts an ID, but the typing is not copied over to `.subscribe()`, even though I think it does actually work.

https://github.com/nbd-wtf/nostr-tools/blob/e398617fdc0013fdbc1e074ab6dbaeeda6ec69bf/abstract-relay.ts#L264-L276

Could we add the `& {id?: string}` type to `.subscribe()`? I'm happy to submit a PR if it's likely to be merged.

**Comment by fiatjaf** [comment]
Yes, please do it.

But now I am curious on why you need to pass a custom subscription id. Is it just to make it easier to read the raw messages and debug?

**Comment by chmac** [comment]
Done.

We're tracking which events are seen on which relays, and so we're sending the same subscription to multiple relays. In that context, I want to set my own subscription IDs and then be sure that they're the same across all the relays (even if the generation of IDs changes in nostr-tools). I also want to replace subscriptions by setting new filters, and to track that, I want to set the ID.

It currently works, I can just type coerce it and the `id` is passed through, but I figured no harm in submitting a PR to fix the types.
