### ISSUE TITLE
Installing with deno add jsr:@nostr/tools returns an error

### ISSUE THREAD

**Issue by gustavonmartins** [nbd-wtf/nostr-tools#459]
I just tried installing with deno 2.1.1 using the command
`deno add jsr:@nostr/tools`

But at the end of the installation I get the error:

```
Add jsr:@nostr/tools@2.10.3
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:es5-ext@0.10.64
┠─ npm:bufferutil@4.0.8
┠─ npm:utf-8-validate@5.0.10
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
error: Could not find dist-tag 'v0.1.0' for npm package 'nostr-wasm'.
    at https://jsr.io/@nostr/tools/2.10.3/wasm.ts:2:36
```

Note the error
```
error: Could not find dist-tag 'v0.1.0' for npm package 'nostr-wasm'.
    at https://jsr.io/@nostr/tools/2.10.3/wasm.ts:2:36
```

Weird is that though there is this error, somehow I can run the lib with no problems

**Comment by alexgleason** [comment]
Install it with `npm:nostr-tools`. The jsr build is broken.

**Comment by gustavonmartins** [comment]
Wouldnt it make sense to remove the instruciton on readme file
npx jsr add @nostr/tools
And also to clarify this on issue #376?
I got the idea of using JSR from there

**Comment by fiatjaf** [comment]
It is not broken anymore. I have installed it with `jsr add @nostr/tools` many times, never encountering this error.

But I understand it now. The nostr-wasm version has a wrong `v` prefix and `npm` "fixes" that when downloading, but `deno` doesn't. Postel's law attacks again in all its stupidity. I'll fix this.
