### ISSUE TITLE
nostr-tools and electron

### ISSUE THREAD

**Issue by wds4** [nbd-wtf/nostr-tools#46]
For anyone trying to get nostr-tools working with electron, I have started a [repo](https://github.com/wds4/electron-react-boilerplate-nostr) which is a fork of [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) in which I am testing out basic nostr-tools functionality. So far, I'm getting at least some of it to work. I'm going to post problems that I encounter either on my repo's README or over here (or both) in the hopes it may be useful to others using electron. (I should mention that electron-react-boilerplate is fairly well fleshed out with bells and whistles, so some of the issues I encounter may stem from interactions with them.)

So far there are two issues that I will summarize briefly:

The first is already fixed in the code and I presume the fix will be in v0.24.2, but it's still a problem in the most recent version which is still v0.24.1. I was getting a type error:
```
Cannot read properties of undefined (reading 'call')
```
with any function that called getEventHash, which is in [event.ts](https://github.com/fiatjaf/nostr-tools/blob/master/event.ts). To fix this I had to dig into that file in node_modules/nostr-tools after installation, add:
```
import {sha256} from '@noble/hashes/sha256'
```
and update getEventHash to 
```
export function getEventHash(event: Event): string {
  let eventHash = sha256(Buffer.from(serializeEvent(event)))
  return Buffer.from(eventHash).toString('hex')
}
```
Like I said - already addressed in the upcoming version, although I don't know when that will be ready.
 
The second issue relates to the topic of [native modules](https://www.electronjs.org/docs/latest/tutorial/using-native-node-modules), which is something I still haven't wrapped my head around. By my understanding, nostr-tools is not a native module, but its dependency tree includes bufferutil and utf-8-validate, both of which are native. So for me to get nostr-tools to work in electron, I had to install it as a devDependency, not a dependency; otherwise, npm install throws an error. More specifically, [this file](https://github.com/wds4/electron-react-boilerplate-nostr/blob/main/.erb/scripts/check-native-dep.js) throws an error when the postinstall script is called. So far I have it working in dev mode, not yet in the packaged app. (I know I need to install nostr-tools in release/app, although I haven't gotten it fully working yet.)

I don't know whether cleaning up the dependency tree to remove the above two native modules is feasible or not. If it is feasible, it might save some headaches for anyone working with electron.

**Comment by wds4** [comment]
First of the 2 issues above now resolved for me with v1.0.0-alpha2

**Comment by fiatjaf** [comment]
I don't understand how there could be native modules if it works in the browser. Maybe these native modules are hybrid and they have a version that works in pure JS.

**Comment by siniradam** [comment]
I couldn't get it work nostr-tools in SvelteKit without bunch of polyfills, and most fixes for below Vite 4, which is the last version of SvelteKit (1.1.0) uses 4.0.
So I ended up making my own implementation. It's a bit slow progress but having a template makes things easy for me. 
I was wondering if this is something similar to it?
Usually stuff like "[Module "util" has been externalized for browser compatibility. Cannot access ... "

**Comment by wds4** [comment]
I was also getting the polyfill error with some import statements, like: 
```
import { generatePrivateKey, getPublicKey } from 'nostr-tools'
```
I discovered a solution [here in stackoverflow](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5). My electron boilerplate uses webpack5, and apparently webpack5 no longer supports polyfills (why? idk). But I managed to fix the problem by adding 
```
fallback: {
  "stream": false,
}
```
under resolve in [webpack.config.base.ts](https://github.com/wds4/electron-react-boilerplate-nostr/blob/main/.erb/configs/webpack.config.base.ts). Why this works I have no idea lol. I'm still in the process of figuring out webpack, polyfills, native dependencies, electron's two-package structure, etc. 

Does Sveltpack use webpack? 

And am I understanding correctly that the purpose of polyfills is to make sure we're using the version (of a hybrid module) that works in JS? I've been running into very [similar issues](https://discuss.ipfs.tech/t/why-does-npm-call-ipfs-core-a-native-dependency/15725/2) when I use ipfs-core with electron-react-boilerplate; it's also javascript but has a dependency called classic-level which triggers the same problem for me with ipfs-core that bufferutil and utf-8-validate are triggering for nostr-tools.

**Comment by siniradam** [comment]
> I was also getting the polyfill error with some import statements, like:
> 
> ```
> import { generatePrivateKey, getPublicKey } from 'nostr-tools'
> ```
> 
> I discovered a solution [here in stackoverflow](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5). My electron boilerplate uses webpack5, and apparently webpack5 no longer supports polyfills (why? idk). But I managed to fix the problem by adding
> 
> ```
> fallback: {
>   "stream": false,
> }
> ```
> 
> under resolve in [webpack.config.base.ts](https://github.com/wds4/electron-react-boilerplate-nostr/blob/main/.erb/configs/webpack.config.base.ts). Why this works I have no idea lol. I'm still in the process of figuring out webpack, polyfills, native dependencies, electron's two-package structure, etc.
> 
> Does Sveltpack use webpack?
> 
> And am I understanding correctly that the purpose of polyfills is to make sure we're using the version (of a hybrid module) that works in JS? I've been running into very [similar issues](https://discuss.ipfs.tech/t/why-does-npm-call-ipfs-core-a-native-dependency/15725/2) when I use ipfs-core with electron-react-boilerplate; it's also javascript but has a dependency called classic-level which triggers the same problem for me with ipfs-core that bufferutil and utf-8-validate are triggering for nostr-tools.

No it't not. It's Vite. 
Some features are not available in the browser, polyfills either supplies browser api version, or suppressing it.

**Comment by fiatjaf** [comment]
I'll close this because it's 2024 and no one uses Electron anymore (just kidding).
