### ISSUE TITLE
nprofile encode length should be larger than 1000

### ISSUE THREAD

**Issue by pseudozach** [nbd-wtf/nostr-tools#74]
we're gonna need a bigger length, for some reason odell's nprofile data including relay list is 1030 in length and that crashes nostr.directory.

need to increase this
https://github.com/nbd-wtf/nostr-tools/blob/master/nip19.ts#L99

![Screen Shot 2023-01-02 at 11 48 57 PM](https://user-images.githubusercontent.com/3731591/210317412-544dfdff-8ffd-4269-86fd-27e99eca7501.png)

**Comment by Bayernatoor** [comment]
If all this needs is the limit increased I can submit a PR. 

Perhaps we'd need to do the same for `encodeBytes` and `neventEncode`? 

afaik increasing the limit simply increases the Bech32 String length. Maybe an increase to 1100? Unless there's a better way to solve this/prevent the length from ever being an issue.

**Comment by fiatjaf** [comment]
Increase it to 1500 while you're at it, but @pseudozach you can perhaps just use the first 2 or 3 relays to make the string not be so large. Your choice.

**Comment by pseudozach** [comment]
> Please increase it to 1500 while you're at it, @Bayernatoor, but @pseudozach you can perhaps just use the first 2 or 3 relays to make the string not be so large. Your choice.

I want to make it realistic because if not people will complain that I'm not showing all their relays or I deleted their relays etc.

There should be no harm in setting this value to 1500, right?

**Comment by fiatjaf** [comment]
I think there is no harm unless you want to make a QR code.

**Comment by pseudozach** [comment]
if I try to use `npm i nbd-wtf/nostr-tools`

I get below errors.  Not sure if these were introduced recently or but I didn't have these on v1.1.0.
>error - ./node_modules/nostr-tools/event.ts
Module parse failed: Unexpected token (7:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| /* eslint-disable no-unused-vars */
> export enum Kind {
|   Metadata = 0,
|   Text = 1,
(node:61945) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)

![Screen Shot 2023-01-03 at 11 16 03 PM](https://user-images.githubusercontent.com/3731591/210503099-b8e04061-b018-4b34-8ad2-122b7aa372cb.png)

**Comment by fiatjaf** [comment]
This is because the latest versions are written in Typescript and you're trying to import Typescript as JS and your Webpack doesn't like that. There are pre-transpiled versions in ESM and CJS published too, your code should be picking those. How does it look like?

**Comment by pseudozach** [comment]
sorry about that irrelevant comment. once npm version is bumped to v1.1.1 issue is resolved. Thanks!

**Comment by pseudozach** [comment]
just reporting that indeed this issue came back for values > 1500. So I'll be doing some limiting on my side instead of continuing to increase this hardcoded value indefinitely.

Although is it better to make this an input parameter? @fiatjaf 

![Screen Shot 2023-01-18 at 11 19 19 AM](https://user-images.githubusercontent.com/3731591/213274287-e70a0875-501f-47de-b0fc-2ff128ae69ba.png)

**Comment by fiatjaf** [comment]
I've increased it to 5000.
