### ISSUE TITLE
Question about status 'ok' vs 'seen' when publishing new event

### ISSUE THREAD

**Issue by MTG2000** [nbd-wtf/nostr-tools#83]
Hi there.

I have a small question regarding the state of a newly published event.

It seems that after publishing a new event, it will first become in an 'ok' state where it "has been accepted by relay", then it'll become in a 'seen' state where it has been "seen on the relay"

But I'm not really sure about the different between the two.
Could an event be accepted by a relay but not "seen" on it??

When I'm building a user journey where there I show a loading spinner while publishing an event, should I end the loading state when I receive the 'ok' state or when I receive the 'seen' state??

-------------------------------------------------------

Another related question.
I noticed that after publishing an event, there will be 2 events returned.
One is the same event that we published, and another that has a `monitor-${id.slice()}` value & also contains the published event.
What is the difference between the two?

Should I care about one and ignore the other or what??

Thanks 🙏

**Comment by fiatjaf** [comment]
The `ok` happens when the relay sends back an `OK` message (NIP-20) but some relays may not send that (although I think most do currently). `seen` happens when receive that event back from the relay.

I think the best thing you can do is just listen for `ok` and if you get that assume all is good; but if that takes too long (say, more than 1 second) then you subscribe to `seen` (and only after you subscribe to `seen` the library will attempt to fetch the event from the relay).

**Comment by MTG2000** [comment]
Ahh, okay. 
Got it.

One interesting point though:
```
(and only after you subscribe to seen the library will attempt to fetch the event from the relay)
```
Does this mean that:
Even if I have an active subscription with filters that apply to the newly created event, this new event won't be fetched UNLESS I'm subscribed to the `seen` ???

Or in other words:
A relay will NOT return an event that I just published to it??

Maybe I just misunderstood that completely... 😅

**Comment by fiatjaf** [comment]
A relay will return an event you just published. The `seen` call only causes your client to open a new subscription specific for that event with the sole purpose of checking if it is on the relay.

**Comment by fiatjaf** [comment]
Closing this because otherwise I will forget to close later, but you can keep asking things if you want.

**Comment by MTG2000** [comment]
> A relay will return an event you just published. The `seen` call only causes your client to open a new subscription specific for that event with the sole purpose of checking if it is on the relay.

Got it 👍 
Everything is clear now.

Thanks a lot for your help @fiatjaf
