### ISSUE TITLE
Make Relay test not dependent on external service

### ISSUE THREAD

**Issue by adamritter** [nbd-wtf/nostr-tools#84]
I made nostr-relaypool-ts tests more deterministic by not depending on external service / internet connection by using an in memory relay pool implementation as a dev dependency. It's just a small improvement (also makes tests run much faster, which can help with development). Feel free to take it if you want:

https://github.com/adamritter/nostr-relaypool-ts/blob/main/in-memory-relay-server.ts

The relay test in nostr-relaypool-ts repo is here:

https://github.com/adamritter/nostr-relaypool-ts/blob/main/relay.test.ts

**Comment by fiatjaf** [comment]
Thank you, that is a good idea, but I don't think it is that important to justify spending time on it at this point.
