### ISSUE TITLE
Idea: Adding support for nip11 relay info

### ISSUE THREAD

**Issue by chmac** [nbd-wtf/nostr-tools#85]
Firstly, thanks for nostr-tools, it makes building on nostr super easy in the browser. 🧡 🧡 🧡 

My idea is to add [nip11](https://github.com/nostr-protocol/nips/blob/master/11.md) support to nostr-tools. The back story is that I was pushing parameterised replaceable events to several relays, until I realised they don't support them (nip33). Then checking nostr.watch it seems that there's only a small subset of relays who support nip33.

My thought was that I'd like my nostr client to automatically reject messages I try to post to relays which don't support those features. Of course I'd also like to be able to override said protections.

Before I go too far down the rabbit hole and start writing PRs, I wanted to check in with the maintainers first. Is this something you think would make sense to add to nostr-tools?

Edit: I can think of lots of different ways nip11 support could be added. The scenario described above is just one of those. I wanted to open the discussion on the whole topic rather than just the idea of rejecting events to relays which won't support them.

**Comment by adamritter** [comment]
As far as I know nop11 is not possible to implement in the browser, because
WebSocket client API doesn't support it.

I think it would be better to change the protocol actually to not contain
features that can't be implemented in the browser.

**Comment by adamritter** [comment]
Ah sorry, you're right, it works.

**Comment by fiatjaf** [comment]
The implementation should be a standalone `nip11.ts` file exporting a function that just makes a request to a relay and returns the data, with the types and so on. Maybe with some helper methods.

To keep everything lean and agnostic we can't mix that into the `relay.js` implementation here, that must be done at higher levels.

**Comment by chmac** [comment]
@fiatjaf Gotcha. So a standalone `nip11.ts` file which handles getting the relay info, etc.

One idea I had was to check relays for nip support before opening the websocket connection. Then to add some filtering on which types of events get broadcast to which relays. Those filters would probably be nip specific. So a filter for nip33 would say something like `kind>=30000&kind<40000`.

Where would you see those filters going? Part of the `nip11.ts` file? Or as a separate export from each of the nip files? Or does this seem like it doesn't fit nostr-tools and would be better implemented as a separate package altogether?

Personally, I kinda like the idea that by default, nostr-tools won't send events to relays which don't support them. Especially with events that should be deleted (whether expired, replaced, whatever), it seems like an unfortunate scenario to accidentally send it to a relay that doesn't support the appropriate nip.

**Comment by giacomogagliano** [comment]
I saw this issue and as I am working on a relay implementation and this nip is about relays I did a nip11.ts with types and a function to get infos from a relay. I also did some tests, here a link to the file I did:

https://github.com/giacomogagliano/nip11/blob/nip11/nip11.ts

hope it can help!

**Comment by fiatjaf** [comment]
Nice, @giacomogagliano, can you open a pull request adding that to this repo?

**Comment by giacomogagliano** [comment]
Yes =), sounds great =)!
