### ISSUE TITLE
Question: Why are lockfiles ignored?

### ISSUE THREAD

**Issue by escapedcat** [nbd-wtf/nostr-tools#87]
https://github.com/nbd-wtf/nostr-tools/blob/master/.gitignore#L3-L4
This will lead to everyone might install different versions of deps/sub-deps which can lead issues you do not run into because your setup is in a certain state, right?

**Comment by escapedcat** [comment]
Alright :P

**Comment by fiatjaf** [comment]
I actually don't understand the purpose of lockfiles? Aren't versions already specified in `package.json`?

**Comment by adamritter** [comment]
No, package.json specifies constraints to the package manager

**Comment by escapedcat** [comment]
For example:

```json
"@noble/hashes": "^0.5.7",
```
https://github.com/nbd-wtf/nostr-tools/blob/master/package.json#L12

This will always install the latest `0.5.x` version. sub-dependencies might change as well.
With a lockfile you make sure everyone get's the same exact versions.

**Comment by fiatjaf** [comment]
What if you write `@noble/hashes: "0.5.7"` instead?

**Comment by escapedcat** [comment]
> What if you write `@noble/hashes: "0.5.7"` instead?

sub-dependencies still might change if i.e. a package says has such dep: `@project/thing: "*"` or also just `"@project/thing: "^1.0.0"`

**Comment by escapedcat** [comment]
From experience not having lockfiles leads to issues eventually. Can't rely on what other projects do.
