### ISSUE TITLE
How to work with existing public key

### ISSUE THREAD

**Issue by cypcz** [nbd-wtf/nostr-tools#95]
Hello, it's clear from the docs how to work with public/private keys when generating them from scratch. I'm trying to figure out how to use the existing public key to pass the `validateEvent` check.

I went through the `nostr-tools` and `@noble/secp256k1` packages and tried to simulate the creating of the keys.

```
import * as secp256k1 from '@noble/secp256k1'
import { utf8Encoder } from 'nostr-tools/utils'

const pubkey = secp256k1.utils.bytesToHex(
  utf8Encoder.encode('npub1yrmj7fe0t5tjffv8e28et7ur27zvrmucmeqytt3w2wdp2tp3la3shpy9pf')
) 

// 6e7075623179726d6a376665307435746a66667638653238657437757232377a76726d75636d6571797474337732776470327470336c613373687079397066
```

Such constructed `pubkey` fails the validation `pubkey.match(/^[a-f0-9]{64}$/)`. 

How should I work with existing public key? Thank you!

**Comment by cypcz** [comment]
Just found NIP19 which probably answers my question.

**Comment by skyrover7** [comment]
> Just found NIP19 which probably answers my question.

@cypcz can you elaborate?

**Comment by fiatjaf** [comment]
All functions expect public keys in hex format (32-bytes as 64 hex characters). To convert between npub and hex use the `nip19` module.

**Comment by skyrover7** [comment]
understood! but if i just want to validate that the provided hex format public key is valid? sorry if it's a noob question

**Comment by fiatjaf** [comment]
`hexkey.match(/^[a-f0-9]{64}$/)`

**Comment by skyrover7** [comment]
> `hexkey.match(/^[a-f0-9]{64}$/)`

appreciate you!
