### ISSUE TITLE
close never resolves if existing connection status is not 1

### ISSUE THREAD

**Issue by sondreb** [nbd-wtf/nostr-tools#98]
## ISSUE
Calling the `close` function on the relay will hang forever.

This can be mitigated by validating the status is 1 before calling close.

## EXPECTED BEHAVIOR

I'm expecting the .close() function to easily handle any current connection status and simply return when connection is closed.

**Comment by jilv220** [comment]
Seems like the problem is slow shutdown. It took me over 1m to close all the connections.

**Comment by fiatjaf** [comment]
I believe this was solved on a commit from yesterday.
