### ISSUE TITLE
Filtering by tags

### ISSUE THREAD

**Issue by cypcz** [nbd-wtf/nostr-tools#99]
Can `nostr-tools` filter by tags? I currently don't see a way to query for reactions to a particular event. Thanks!

**Comment by fiatjaf** [comment]
Yes, just pass `#tag` to the filter.

**Comment by flashtea** [comment]
I have a problem with the tag filtering.
I am implementing NIP-28 using the e tag to differentiate between root and reply messages.
I also add the Channel id as e tag.

Root message:
```
tags: [  
  ['t', <custom-tag>]
  ['e', <channel-id>, <relay>, 'root']
]
```
Reply:
```
tags: [
  ['t', <custom-tag>]
  ['e', <channel-id>, <relay>, 'reply'],
  ['p', <parent-id>]
]
```

Unfortunately i only get results querying by the ```channel-id``` if i add 'root' or 'reply' i get no results:
```
const filter: Filter = {
      kinds: [42],
      '#t': [<costom-tag>],
      '#e': [<channel-id>, 'root']   // only works without 'root'
};
```

Is this a issue with relays handling the requests (result objects, without querying by 'root', do contain the right tags) or am i misusing the library/nostr specification?
